SELECT 
  CASE 
    WHEN TIMESTAMPDIFF(YEAR, u.BIRTH_DATE, CURDATE()) BETWEEN 18 AND 25 THEN 'Gen Z'
    WHEN TIMESTAMPDIFF(YEAR, u.BIRTH_DATE, CURDATE()) BETWEEN 26 AND 40 THEN 'Millennials'
    WHEN TIMESTAMPDIFF(YEAR, u.BIRTH_DATE, CURDATE()) BETWEEN 41 AND 56 THEN 'Gen X'
    ELSE 'Boomers'
  END AS GENERATION,
  SUM(t.FINAL_SALE) AS TOTAL_SALES,
  (SUM(t.FINAL_SALE) * 100.0 / (SELECT SUM(FINAL_SALE) FROM Transactions)) AS PERCENTAGE
FROM Transactions t
JOIN Users u ON t.USER_ID = u.ID
JOIN Products p ON t.BARCODE = p.BARCODE
WHERE p.CATEGORY_1 = 'Health & Wellness'
GROUP BY GENERATION
ORDER BY PERCENTAGE DESC;