SELECT p.BRAND, COUNT(t.RECEIPT_ID) AS RECEIPT_COUNT
FROM Transactions t
JOIN Users u ON t.USER_ID = u.ID
JOIN Products p ON t.BARCODE = p.BARCODE
WHERE TIMESTAMPDIFF(YEAR, u.BIRTH_DATE, CURDATE()) >= 21
GROUP BY p.BRAND
ORDER BY RECEIPT_COUNT DESC
LIMIT 5;